trigger:
  branches:
    include:
      - main
  paths:
    include:
      - kjeldsen.backend/**
      - kjeldsen.frontend/**

pool: Default

variables:
  - group: site

  configuration: 'Release'
  backendProject: 'kjeldsen.backend/kjeldsen.backend.csproj'
  frontendDirectory: 'kjeldsen.frontend'
  azureSubscription: 'kjeldsen.dev'
  resourceGroup: 'kjdev-rg'
  webAppNameCm: 'kjdev-app-backoffice'
  webAppNameFrontend: 'kjdev-app-frontend'

stages:
  - stage: BuildFrontend
    displayName: 'Build Frontend (Nuxt)'
    condition: |
      or(
        contains(variables['Build.TriggeredByChanges'], 'kjeldsen.frontend'),
        eq(variables['Build.Reason'], 'Manual')
      )
    jobs:
      - job: BuildAndPublishFrontend
        displayName: 'Build and Publish Frontend'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - task: PowerShell@2
            displayName: 'Generate .env file from Key Vault secrets'
            inputs:
              targetType: 'inline'
              script: |
                $ErrorActionPreference = "Stop"

                $mappingFile = "$(frontendDirectory)/secret-keys.json"
                $envFilePath = "$(frontendDirectory)/.env"

                Write-Host "Reading secret mapping from: $mappingFile"
                $json = Get-Content -Raw -Path $mappingFile | ConvertFrom-Json

                $envLines = @()

                foreach ($item in $json) {
                    $sourceKey = $item.key
                    $targetKey = $item.as

                    $secretValue = $env:$sourceKey
                    if (-not $secretValue) {
                        Write-Warning "No value found for secret key: $sourceKey"
                        continue
                    }

                    $line = "$targetKey=$secretValue"
                    Write-Host "Writing $targetKey from $sourceKey"
                    $envLines += $line
                }

                $envLines | Out-File -FilePath $envFilePath -Encoding UTF8 -Force
                Write-Host "✅ .env file created at $envFilePath"

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                cd "$(frontendDirectory)"
                npm ci
                npm run build
            displayName: 'Install dependencies and build Nuxt (PS)'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(frontendDirectory)/.output'
              artifactName: 'frontend'
            displayName: 'Publish frontend artifact'

          - task: AzureWebApp@1
            displayName: 'Deploy Frontend to Azure App Service'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(webAppNameFrontend)'
              package: '$(frontendDirectory)/.output'
              appType: 'webApp'
              deploymentMethod: 'zipDeploy'

  - stage: BuildBackend
    displayName: 'Build and Deploy Umbraco Backend'
    dependsOn: BuildFrontend
    jobs:
      - job: BuildAndPublishBackend
        displayName: 'Build and Publish Umbraco Artifact'
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET SDK'
            inputs:
              packageType: 'sdk'
              version: '9.x'
              includePreviewVersions: true

          - task: DotNetCoreCLI@2
            displayName: 'Publish Umbraco (Trimmed)'
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: '$(backendProject)'
              arguments: >
                --configuration $(configuration)
                --output $(Build.ArtifactStagingDirectory)/umbraco
                /p:SelfContained=false
                /p:RuntimeIdentifier=win-x86
                /p:PublishReadyToRun=true
                /p:EnableCompressionInSingleFile=true
              zipAfterPublish: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Umbraco Artifact'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/umbraco'
              artifactName: 'umbraco'

      - job: DeployBackend
        displayName: 'Deploy Umbraco to Azure App Service'
        dependsOn: BuildAndPublishBackend
        steps:
          - download: current
            artifact: umbraco
            displayName: 'Download Umbraco Artifact'

          - task: AzureRmWebAppDeployment@5
            displayName: 'Deploy Umbraco CM to Azure App Service'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              WebAppName: '$(webAppNameCm)'
              packageForLinux: '$(Pipeline.Workspace)/umbraco/*.zip'
              enableCustomDeployment: true
              DeploymentType: 'zipDeploy'
