// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetSegmentationAssetsItemByIdData, GetSegmentationAssetsItemByIdErrors, GetSegmentationAssetsItemByIdResponses, GetSegmentationAssetsItemByPathData, GetSegmentationAssetsItemByPathErrors, GetSegmentationAssetsItemByPathResponses, GetSegmentationContentActivesegmentsByIdData, GetSegmentationContentActivesegmentsByIdErrors, GetSegmentationContentActivesegmentsByIdResponses, GetSegmentationContentActivesegmentsByPathData, GetSegmentationContentActivesegmentsByPathErrors, GetSegmentationContentActivesegmentsByPathResponses, GetSegmentationContentSegmentsByIdData, GetSegmentationContentSegmentsByIdResponses, GetSegmentationContentSegmentsByPathData, GetSegmentationContentSegmentsByPathResponses, GetSegmentationContentSegmentsData, GetSegmentationContentSegmentsResponses, GetUmbracoEngageextensionsPageviewRulesData, GetUmbracoEngageextensionsPageviewRulesResponses, GetUmbracoEngageextensionsPageviewScoresData, GetUmbracoEngageextensionsPageviewScoresResponses, PostAnalyticsPageeventTrackpageeventData, PostAnalyticsPageeventTrackpageeventErrors, PostAnalyticsPageeventTrackpageeventResponses, PostAnalyticsPageviewTrackpageviewClientData, PostAnalyticsPageviewTrackpageviewClientErrors, PostAnalyticsPageviewTrackpageviewClientResponses, PostAnalyticsPageviewTrackpageviewServerData, PostAnalyticsPageviewTrackpageviewServerErrors, PostAnalyticsPageviewTrackpageviewServerResponses, PostUmbracoEngageextensionsPageviewRegisterData, PostUmbracoEngageextensionsPageviewRegisterErrors, PostUmbracoEngageextensionsPageviewRegisterResponses, PostUmbracoEngageextensionsPageviewSneakySegmentCheckData, PostUmbracoEngageextensionsPageviewSneakySegmentCheckResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const postUmbracoEngageextensionsPageviewSneakySegmentCheck = <ThrowOnError extends boolean = false>(options: Options<PostUmbracoEngageextensionsPageviewSneakySegmentCheckData, ThrowOnError>): RequestResult<PostUmbracoEngageextensionsPageviewSneakySegmentCheckResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostUmbracoEngageextensionsPageviewSneakySegmentCheckResponses, unknown, ThrowOnError>({
    url: '/umbraco/engageextensions/pageview/sneaky-segment-check',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getUmbracoEngageextensionsPageviewScores = <ThrowOnError extends boolean = false>(options?: Options<GetUmbracoEngageextensionsPageviewScoresData, ThrowOnError>): RequestResult<GetUmbracoEngageextensionsPageviewScoresResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetUmbracoEngageextensionsPageviewScoresResponses, unknown, ThrowOnError>({ url: '/umbraco/engageextensions/pageview/scores', ...options });

export const getUmbracoEngageextensionsPageviewRules = <ThrowOnError extends boolean = false>(options?: Options<GetUmbracoEngageextensionsPageviewRulesData, ThrowOnError>): RequestResult<GetUmbracoEngageextensionsPageviewRulesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetUmbracoEngageextensionsPageviewRulesResponses, unknown, ThrowOnError>({ url: '/umbraco/engageextensions/pageview/rules', ...options });

export const postUmbracoEngageextensionsPageviewRegister = <ThrowOnError extends boolean = false>(options: Options<PostUmbracoEngageextensionsPageviewRegisterData, ThrowOnError>): RequestResult<PostUmbracoEngageextensionsPageviewRegisterResponses, PostUmbracoEngageextensionsPageviewRegisterErrors, ThrowOnError> => (options.client ?? client).post<PostUmbracoEngageextensionsPageviewRegisterResponses, PostUmbracoEngageextensionsPageviewRegisterErrors, ThrowOnError>({
    url: '/umbraco/engageextensions/pageview/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getSegmentationContentActivesegmentsById = <ThrowOnError extends boolean = false>(options: Options<GetSegmentationContentActivesegmentsByIdData, ThrowOnError>): RequestResult<GetSegmentationContentActivesegmentsByIdResponses, GetSegmentationContentActivesegmentsByIdErrors, ThrowOnError> => (options.client ?? client).get<GetSegmentationContentActivesegmentsByIdResponses, GetSegmentationContentActivesegmentsByIdErrors, ThrowOnError>({ url: '/umbraco/engage/api/v1/segmentation/content/activesegments/{id}', ...options });

export const getSegmentationContentActivesegmentsByPath = <ThrowOnError extends boolean = false>(options: Options<GetSegmentationContentActivesegmentsByPathData, ThrowOnError>): RequestResult<GetSegmentationContentActivesegmentsByPathResponses, GetSegmentationContentActivesegmentsByPathErrors, ThrowOnError> => (options.client ?? client).get<GetSegmentationContentActivesegmentsByPathResponses, GetSegmentationContentActivesegmentsByPathErrors, ThrowOnError>({ url: '/umbraco/engage/api/v1/segmentation/content/activesegments/{path}', ...options });

export const getSegmentationContentSegments = <ThrowOnError extends boolean = false>(options?: Options<GetSegmentationContentSegmentsData, ThrowOnError>): RequestResult<GetSegmentationContentSegmentsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetSegmentationContentSegmentsResponses, unknown, ThrowOnError>({ url: '/umbraco/engage/api/v1/segmentation/content/segments', ...options });

export const getSegmentationContentSegmentsById = <ThrowOnError extends boolean = false>(options: Options<GetSegmentationContentSegmentsByIdData, ThrowOnError>): RequestResult<GetSegmentationContentSegmentsByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetSegmentationContentSegmentsByIdResponses, unknown, ThrowOnError>({ url: '/umbraco/engage/api/v1/segmentation/content/segments/{id}', ...options });

export const getSegmentationContentSegmentsByPath = <ThrowOnError extends boolean = false>(options: Options<GetSegmentationContentSegmentsByPathData, ThrowOnError>): RequestResult<GetSegmentationContentSegmentsByPathResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetSegmentationContentSegmentsByPathResponses, unknown, ThrowOnError>({ url: '/umbraco/engage/api/v1/segmentation/content/segments/{path}', ...options });

export const getSegmentationAssetsItemById = <ThrowOnError extends boolean = false>(options: Options<GetSegmentationAssetsItemByIdData, ThrowOnError>): RequestResult<GetSegmentationAssetsItemByIdResponses, GetSegmentationAssetsItemByIdErrors, ThrowOnError> => (options.client ?? client).get<GetSegmentationAssetsItemByIdResponses, GetSegmentationAssetsItemByIdErrors, ThrowOnError>({ url: '/umbraco/engage/api/v1/segmentation/assets/item/{id}', ...options });

export const getSegmentationAssetsItemByPath = <ThrowOnError extends boolean = false>(options: Options<GetSegmentationAssetsItemByPathData, ThrowOnError>): RequestResult<GetSegmentationAssetsItemByPathResponses, GetSegmentationAssetsItemByPathErrors, ThrowOnError> => (options.client ?? client).get<GetSegmentationAssetsItemByPathResponses, GetSegmentationAssetsItemByPathErrors, ThrowOnError>({ url: '/umbraco/engage/api/v1/segmentation/assets/item/{path}', ...options });

export const postAnalyticsPageviewTrackpageviewClient = <ThrowOnError extends boolean = false>(options: Options<PostAnalyticsPageviewTrackpageviewClientData, ThrowOnError>): RequestResult<PostAnalyticsPageviewTrackpageviewClientResponses, PostAnalyticsPageviewTrackpageviewClientErrors, ThrowOnError> => (options.client ?? client).post<PostAnalyticsPageviewTrackpageviewClientResponses, PostAnalyticsPageviewTrackpageviewClientErrors, ThrowOnError>({
    url: '/umbraco/engage/api/v1/analytics/pageview/trackpageview/client',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postAnalyticsPageeventTrackpageevent = <ThrowOnError extends boolean = false>(options: Options<PostAnalyticsPageeventTrackpageeventData, ThrowOnError>): RequestResult<PostAnalyticsPageeventTrackpageeventResponses, PostAnalyticsPageeventTrackpageeventErrors, ThrowOnError> => (options.client ?? client).post<PostAnalyticsPageeventTrackpageeventResponses, PostAnalyticsPageeventTrackpageeventErrors, ThrowOnError>({
    url: '/umbraco/engage/api/v1/analytics/pageevent/trackpageevent',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postAnalyticsPageviewTrackpageviewServer = <ThrowOnError extends boolean = false>(options: Options<PostAnalyticsPageviewTrackpageviewServerData, ThrowOnError>): RequestResult<PostAnalyticsPageviewTrackpageviewServerResponses, PostAnalyticsPageviewTrackpageviewServerErrors, ThrowOnError> => (options.client ?? client).post<PostAnalyticsPageviewTrackpageviewServerResponses, PostAnalyticsPageviewTrackpageviewServerErrors, ThrowOnError>({
    url: '/umbraco/engage/api/v1/analytics/pageview/trackpageview/server',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
