// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44375' | (string & {});
};

export type AbTestVariantModel = {
    id?: number;
    unique?: string;
    name?: null | string;
    description?: null | string;
    redirectNodeKey?: null | string;
    css?: null | string;
    javascript?: null | string;
    created?: string;
    createdByUmbracoUserKey?: string;
    disabled?: null | string;
    disabledByUmbracoUserKey?: null | string;
    isDisabled?: boolean;
    isBenchmark?: boolean;
    totalPageviewsForVariant?: number;
    totalVisitorsForVariant?: number;
    segment?: null | string;
    previewSegment?: null | string;
};

export type AddressFamily = 'Unspecified' | 'Unix' | 'InterNetwork' | 'ImpLink' | 'Pup' | 'Chaos' | 'NS' | 'Ipx' | 'Iso' | 'Osi' | 'Ecma' | 'DataKit' | 'Ccitt' | 'Sna' | 'DecNet' | 'DataLink' | 'Lat' | 'HyperChannel' | 'AppleTalk' | 'NetBios' | 'VoiceView' | 'FireFox' | 'Banyan' | 'Atm' | 'InterNetworkV6' | 'Cluster' | 'Ieee12844' | 'Irda' | 'NetworkDesigners' | 'Max' | 'Packet' | 'ControllerAreaNetwork' | 'Unknown';

export type AppliedPersonalizationContentTypeModel = {
    id?: number;
    key?: string;
    contentTypeId?: number;
    culture?: null | string;
};

export type AppliedPersonalizationModel = {
    id?: number;
    key?: string;
    segmentId?: null | number;
    umbracoSegmentAlias?: null | string;
    previewSegment?: null | string;
    type?: null | AppliedPersonalizationTypeModel;
    name?: null | string;
    description?: null | string;
    css?: null | string;
    javascript?: null | string;
    started?: null | string;
    isActive?: boolean;
    created?: string;
    createdByUmbracoUserKey?: string;
    updated?: null | string;
    updatedByUmbracoUserKey?: null | string;
    pages?: Array<AppliedPersonalizationUmbracoPageVariantModel>;
    contentTypes?: Array<AppliedPersonalizationContentTypeModel>;
};

export type AppliedPersonalizationTypeModel = 'SinglePage' | 'MultiPage' | 'ContentType';

export type AppliedPersonalizationUmbracoPageVariantModel = {
    id?: number;
    key?: string;
    nodeId?: number;
    nodeKey?: null | string;
    culture?: null | string;
};

export type AsnEncodedData = {
    oid?: null | Oid;
    rawData?: string;
};

export type AssetsResponseModel = {
    javascript?: null | Array<string>;
    css?: null | Array<string>;
};

export type AsymmetricAlgorithm = {
    keySize?: number;
    legalKeySizes?: null | Array<KeySizes>;
    signatureAlgorithm?: null | string;
    keyExchangeAlgorithm?: null | string;
};

export type BrowserModel = {
    name?: null | string;
    version?: null | string;
    created?: string;
};

export type CancellationToken = {
    isCancellationRequested?: boolean;
    canBeCanceled?: boolean;
    waitHandle?: WaitHandle;
};

export type Claim = {
    issuer?: null | string;
    originalIssuer?: null | string;
    properties?: null | {
        [key: string]: string;
    };
    subject?: ClaimsIdentity;
    type?: null | string;
    value?: null | string;
    valueType?: null | string;
};

export type ClaimsIdentity = {
    authenticationType?: null | string;
    isAuthenticated?: boolean;
    actor?: null | ClaimsIdentity;
    bootstrapContext?: unknown;
    claims?: unknown;
    label?: null | string;
    name?: null | string;
    nameClaimType?: null | string;
    roleClaimType?: null | string;
};

export type ClaimsPrincipal = {
    claims?: null | Array<Claim>;
    identities?: null | Array<ClaimsIdentity>;
    identity?: IIdentity;
};

export type ConnectionInfo = {
    id?: string;
    remoteIpAddress?: null | IpAddress;
    remotePort?: number;
    localIpAddress?: null | IpAddress;
    localPort?: number;
    clientCertificate?: null | X509Certificate2;
};

export type CustomerJourneyStepScoreModel = unknown;

export type DeviceModel = {
    browser?: BrowserModel;
    operatingSystem?: OperatingSystemModel;
    screen?: ScreenModel;
    deviceType?: DeviceTypeModel;
    defaultVisitorType?: VisitorTypeModel;
    useragent?: null | string;
};

export type DeviceTypeModel = 'Unknown' | 'Desktop' | 'Tablet' | 'Mobile' | 'Console' | 'TV' | 'CarBrowser' | 'SmartDisplay' | 'Camera' | 'PortableMediaPlayer' | 'Phablet' | 'SmartSpeaker' | 'Wearable';

export type GoalCompletionModel = unknown;

export type HostString = {
    value?: null | string;
    hasValue?: boolean;
    host?: null | string;
    port?: null | number;
};

export type HttpContext = {
    features?: null | Array<KeyValuePairOfTypeAndObject>;
    request?: HttpRequest;
    response?: HttpResponse;
    connection?: ConnectionInfo;
    webSockets?: WebSocketManager;
    user?: ClaimsPrincipal;
    items?: {
        [key: string]: unknown;
    };
    requestServices?: IServiceProvider;
    requestAborted?: CancellationToken;
    traceIdentifier?: string;
    session?: ISession;
};

export type HttpRequest = {
    httpContext?: HttpContext;
    method?: string;
    scheme?: string;
    isHttps?: boolean;
    host?: HostString;
    pathBase?: PathString;
    path?: PathString;
    queryString?: QueryString;
    query?: Array<KeyValuePairOfstringAndStringValues>;
    protocol?: string;
    headers?: null | {
        [key: string]: Array<string>;
    };
    cookies?: Array<KeyValuePairOfstringAndstring>;
    contentLength?: null | number;
    contentType?: null | string;
    body?: Stream;
    bodyReader?: PipeReader;
    hasFormContentType?: boolean;
    form?: Array<KeyValuePairOfstringAndStringValues>;
    routeValues?: {
        [key: string]: unknown;
    };
};

export type HttpResponse = {
    httpContext?: HttpContext;
    statusCode?: number;
    headers?: null | {
        [key: string]: Array<string>;
    };
    body?: Stream;
    bodyWriter?: PipeWriter;
    contentLength?: null | number;
    contentType?: null | string;
    cookies?: IResponseCookies;
    hasStarted?: boolean;
};

export type IIdentity = {
    name?: null | string;
    authenticationType?: null | string;
    isAuthenticated?: boolean;
};

export type IpAddress = {
    addressFamily?: AddressFamily;
    scopeId?: number;
    isIPv6Multicast?: boolean;
    isIPv6LinkLocal?: boolean;
    isIPv6SiteLocal?: boolean;
    isIPv6Teredo?: boolean;
    isIPv6UniqueLocal?: boolean;
    isIPv4MappedToIPv6?: boolean;
    address?: number;
};

export type IpAddressModel = {
    ipAddress?: null | string;
    location?: LocationModel;
};

export type IResponseCookies = {
    [key: string]: unknown;
};

export type IServiceProvider = {
    [key: string]: unknown;
};

export type ISession = {
    isAvailable?: boolean;
    id?: null | string;
    keys?: null | Array<string>;
};

export type KeySizes = {
    minSize: number;
    maxSize: number;
    skipSize: number;
};

export type KeyValuePairOfstringAndstring = {
    key: null | string;
    value: null | string;
};

export type KeyValuePairOfstringAndStringValues = {
    key: null | string;
    value: Array<string>;
};

export type KeyValuePairOfTypeAndObject = {
    key: Type;
    value: unknown;
};

export type LocationModel = {
    country?: null | string;
    county?: null | string;
    province?: null | string;
    city?: null | string;
};

export type NotPermittedDueToLicenseResultModel = {
    [key: string]: unknown;
};

export type Oid = {
    value?: null | string;
    friendlyName?: null | string;
};

export type OperatingSystemModel = {
    name?: null | string;
    label?: null | string;
    version?: null | string;
    platform?: null | string;
    created?: string;
};

export type PageEventRequestModel = {
    category: string;
    action?: string;
    label?: string;
    timestamp?: null | string;
};

export type PageModel = {
    id?: number;
    protocol?: null | string;
    domain?: null | string;
    path?: null | string;
    queryString?: null | string;
    port?: number;
    isInternalPage?: boolean;
};

export type PageviewModel = {
    id?: number;
    guid?: string;
    timestamp?: string;
    externalId?: null | string;
    session?: SessionModel;
    ipAddress?: IpAddressModel;
    page?: null | PageModel;
    referrerPage?: PageModel;
    utmCodes?: UtmCodesModel;
    searchQueries?: null | Array<SearchQueryModel>;
    umbracoPageVariant?: null | UmbracoPageVariantModel;
    umbracoMemberKey?: null | string;
    wasPersonalized?: boolean;
    abTestVariants?: null | Array<AbTestVariantModel>;
    appliedPersonalization?: AppliedPersonalizationModel;
    pageviewSegments?: null | Array<PageviewSegmentModel>;
    personaScores?: null | Array<PersonaScoreModel>;
    customerJourneyStepScores?: null | Array<CustomerJourneyStepScoreModel>;
    goalCompletions?: null | Array<GoalCompletionModel>;
    millisecondsOnPage?: null | number;
    requirePingValidation?: boolean;
};

export type PageviewSegmentModel = {
    id?: number;
    pageview: PageviewModel;
    segment: SegmentModel;
};

export type PathString = {
    value?: null | string;
    hasValue?: boolean;
};

export type PersonaScoreModel = unknown;

export type PipeReader = null | Blob | File;

export type PipeWriter = {
    canGetUnflushedBytes?: boolean;
    unflushedBytes?: number;
};

export type PublicKey = {
    encodedKeyValue?: AsnEncodedData;
    encodedParameters?: AsnEncodedData;
    key?: AsymmetricAlgorithm;
    oid?: Oid;
};

export type QueryString = {
    value?: null | string;
    hasValue?: boolean;
};

export type ReadOnlyMemoryOfbyte = string;

export type RemotePageViewClientRequestModel = {
    url: string;
    referrerUrl?: string;
};

export type RemotePageViewResponseModel = {
    externalVisitorId: null | string;
    pageviewId: null | string;
};

export type RemotePageViewServerRequestModel = {
    headers?: string;
    browserUserAgent?: string;
    remoteClientAddress?: string;
    userIdentifier?: string;
    url: string;
    referrerUrl?: string;
};

export type SafeWaitHandle = {
    isInvalid?: boolean;
    isClosed?: boolean;
};

export type ScreenModel = {
    width?: number;
    height?: number;
    pixelDepth?: null | number;
    colorDepth?: null | number;
};

export type SearchQueryModel = {
    id?: number;
    pageviewId?: number;
    query?: null | string;
    timestamp?: string;
    searchBox?: null | string;
    category?: null | string;
};

export type SegmentDetailsResponseModel = {
    umbracoSegmentAlias: null | string;
    segmentId: null | number;
    segmentName: null | string;
    segmentType?: null | string;
    segmentApplicationType?: null | string;
};

export type SegmentedContentListResponseModel = {
    segmentedContent?: null | Array<SegmentedContentResponseModel>;
};

export type SegmentedContentResponseModel = {
    contentTypeAlias?: null | string;
    contentId?: number;
    contentGuid?: string;
    contentUrls?: null | Array<string>;
    segments?: Array<SegmentDetailsResponseModel>;
};

export type SegmentModel = {
    id?: number;
    key?: string;
    name?: null | string;
    description?: null | string;
    created?: string;
    createdByUmbracoUserKey?: string;
    updated?: null | string;
    updatedByUmbracoUserKey?: null | string;
    endTime?: null | string;
    isTemporary?: boolean;
    sortOrder?: number;
    controlGroupSize?: number;
    isActive?: boolean;
    rules?: null | Array<SegmentRuleModel>;
};

export type SegmentRuleModel = {
    id?: number;
    key?: string;
    segmentId?: number;
    type?: null | string;
    config?: null | string;
    isNegation?: boolean;
    created?: string;
    updated?: null | string;
    hasStaleReferences?: boolean;
    validationMode?: SegmentRuleValidationModeModel;
};

export type SegmentRuleValidationModeModel = 'Always' | 'Once' | 'IfFalse' | 'IfTrue';

export type SessionModel = {
    id?: number;
    timestamp?: string;
    sequenceNumber?: number;
    device?: DeviceModel;
    visitor?: VisitorModel;
    pageviewCount?: number;
};

export type SneakySegmentCheck = {
    externalVisitorId?: string;
    url?: string;
    referrerUrl?: string;
    headers?: string;
    remoteClientAddress?: string;
    browserUserAgent?: string;
};

export type StatusCodeResult = {
    statusCode: number;
};

export type Stream = Blob | File;

export type Type = unknown;

export type UmbracoPageVariantModel = {
    contentId?: number;
    culture?: null | string;
    segment?: null | string;
    contentTypeId?: number;
};

export type UtmCodesModel = {
    source?: null | string;
    medium?: null | string;
    campaign?: null | string;
    term?: null | string;
    content?: null | string;
    sourcePlatform?: null | string;
    creativeFormat?: null | string;
    marketingTactic?: null | string;
};

export type VisitorModel = {
    id?: number;
    externalId?: string;
    created?: string;
    visitorType?: VisitorTypeModel;
    lastActiveOn?: null | string;
    identifiedOn?: null | string;
};

export type VisitorTypeModel = 'Person' | 'Bot' | 'Monitor' | 'Spam';

export type WaitHandle = {
    handle?: unknown;
    safeWaitHandle?: null | SafeWaitHandle;
};

export type WebSocketManager = {
    isWebSocketRequest?: boolean;
    webSocketRequestedProtocols?: null | Array<string>;
};

export type X500DistinguishedName = {
    name?: null | string;
    oid?: null | Oid;
    rawData?: string;
};

export type X509Certificate2 = {
    archived?: boolean;
    extensions?: null | Array<X509Extension>;
    friendlyName?: string;
    hasPrivateKey?: boolean;
    privateKey?: null | AsymmetricAlgorithm;
    issuerName?: X500DistinguishedName;
    notAfter?: string;
    notBefore?: string;
    publicKey?: PublicKey;
    rawData?: null | string;
    rawDataMemory?: ReadOnlyMemoryOfbyte;
    serialNumber?: null | string;
    signatureAlgorithm?: Oid;
    subjectName?: X500DistinguishedName;
    thumbprint?: null | string;
    version?: number;
    handle?: unknown;
    issuer?: null | string;
    subject?: null | string;
    serialNumberBytes?: ReadOnlyMemoryOfbyte;
};

export type X509Extension = {
    critical?: boolean;
    oid?: null | Oid;
    rawData?: string;
};

export type PostUmbracoEngageextensionsPageviewSneakySegmentCheckData = {
    body: SneakySegmentCheck;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/umbraco/engageextensions/pageview/sneaky-segment-check';
};

export type PostUmbracoEngageextensionsPageviewSneakySegmentCheckResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoEngageextensionsPageviewScoresData = {
    body?: never;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
    };
    path?: never;
    query?: {
        externalVisitorId?: string;
    };
    url: '/umbraco/engageextensions/pageview/scores';
};

export type GetUmbracoEngageextensionsPageviewScoresResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoEngageextensionsPageviewRulesData = {
    body?: never;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
    };
    path?: never;
    query?: {
        path?: string;
    };
    url: '/umbraco/engageextensions/pageview/rules';
};

export type GetUmbracoEngageextensionsPageviewRulesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostUmbracoEngageextensionsPageviewRegisterData = {
    body: RemotePageViewServerRequestModel;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
        /**
         * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
         */
        'External-Visitor-Id'?: string;
    };
    path?: never;
    query?: never;
    url: '/umbraco/engageextensions/pageview/register';
};

export type PostUmbracoEngageextensionsPageviewRegisterErrors = {
    /**
     * Payment Required
     */
    402: NotPermittedDueToLicenseResultModel;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: StatusCodeResult;
};

export type PostUmbracoEngageextensionsPageviewRegisterError = PostUmbracoEngageextensionsPageviewRegisterErrors[keyof PostUmbracoEngageextensionsPageviewRegisterErrors];

export type PostUmbracoEngageextensionsPageviewRegisterResponses = {
    /**
     * OK
     */
    200: RemotePageViewResponseModel;
};

export type PostUmbracoEngageextensionsPageviewRegisterResponse = PostUmbracoEngageextensionsPageviewRegisterResponses[keyof PostUmbracoEngageextensionsPageviewRegisterResponses];

export type GetSegmentationContentActivesegmentsByIdData = {
    body?: never;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
         */
        'External-Visitor-Id'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/engage/api/v1/segmentation/content/activesegments/{id}';
};

export type GetSegmentationContentActivesegmentsByIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetSegmentationContentActivesegmentsByIdResponses = {
    /**
     * OK
     */
    200: SegmentedContentResponseModel;
};

export type GetSegmentationContentActivesegmentsByIdResponse = GetSegmentationContentActivesegmentsByIdResponses[keyof GetSegmentationContentActivesegmentsByIdResponses];

export type GetSegmentationContentActivesegmentsByPathData = {
    body?: never;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
         */
        'External-Visitor-Id'?: string;
    };
    path: {
        path: string;
    };
    query?: never;
    url: '/umbraco/engage/api/v1/segmentation/content/activesegments/{path}';
};

export type GetSegmentationContentActivesegmentsByPathErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetSegmentationContentActivesegmentsByPathResponses = {
    /**
     * OK
     */
    200: SegmentedContentResponseModel;
};

export type GetSegmentationContentActivesegmentsByPathResponse = GetSegmentationContentActivesegmentsByPathResponses[keyof GetSegmentationContentActivesegmentsByPathResponses];

export type GetSegmentationContentSegmentsData = {
    body?: never;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/umbraco/engage/api/v1/segmentation/content/segments';
};

export type GetSegmentationContentSegmentsResponses = {
    /**
     * OK
     */
    200: SegmentedContentListResponseModel;
};

export type GetSegmentationContentSegmentsResponse = GetSegmentationContentSegmentsResponses[keyof GetSegmentationContentSegmentsResponses];

export type GetSegmentationContentSegmentsByIdData = {
    body?: never;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/engage/api/v1/segmentation/content/segments/{id}';
};

export type GetSegmentationContentSegmentsByIdResponses = {
    /**
     * OK
     */
    200: SegmentedContentResponseModel;
};

export type GetSegmentationContentSegmentsByIdResponse = GetSegmentationContentSegmentsByIdResponses[keyof GetSegmentationContentSegmentsByIdResponses];

export type GetSegmentationContentSegmentsByPathData = {
    body?: never;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
    };
    path: {
        path: string;
    };
    query?: never;
    url: '/umbraco/engage/api/v1/segmentation/content/segments/{path}';
};

export type GetSegmentationContentSegmentsByPathResponses = {
    /**
     * OK
     */
    200: SegmentedContentResponseModel;
};

export type GetSegmentationContentSegmentsByPathResponse = GetSegmentationContentSegmentsByPathResponses[keyof GetSegmentationContentSegmentsByPathResponses];

export type GetSegmentationAssetsItemByIdData = {
    body?: never;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
         */
        'External-Visitor-Id'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/engage/api/v1/segmentation/assets/item/{id}';
};

export type GetSegmentationAssetsItemByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetSegmentationAssetsItemByIdResponses = {
    /**
     * OK
     */
    200: AssetsResponseModel;
};

export type GetSegmentationAssetsItemByIdResponse = GetSegmentationAssetsItemByIdResponses[keyof GetSegmentationAssetsItemByIdResponses];

export type GetSegmentationAssetsItemByPathData = {
    body?: never;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
         */
        'External-Visitor-Id'?: string;
    };
    path: {
        path: string;
    };
    query?: never;
    url: '/umbraco/engage/api/v1/segmentation/assets/item/{path}';
};

export type GetSegmentationAssetsItemByPathErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetSegmentationAssetsItemByPathResponses = {
    /**
     * OK
     */
    200: AssetsResponseModel;
};

export type GetSegmentationAssetsItemByPathResponse = GetSegmentationAssetsItemByPathResponses[keyof GetSegmentationAssetsItemByPathResponses];

export type PostAnalyticsPageviewTrackpageviewClientData = {
    body: RemotePageViewClientRequestModel;
    headers?: {
        'User-Agent'?: string;
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
        /**
         * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
         */
        'External-Visitor-Id'?: string;
    };
    path?: never;
    query?: never;
    url: '/umbraco/engage/api/v1/analytics/pageview/trackpageview/client';
};

export type PostAnalyticsPageviewTrackpageviewClientErrors = {
    /**
     * Payment Required
     */
    402: NotPermittedDueToLicenseResultModel;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostAnalyticsPageviewTrackpageviewClientError = PostAnalyticsPageviewTrackpageviewClientErrors[keyof PostAnalyticsPageviewTrackpageviewClientErrors];

export type PostAnalyticsPageviewTrackpageviewClientResponses = {
    /**
     * OK
     */
    200: RemotePageViewResponseModel;
};

export type PostAnalyticsPageviewTrackpageviewClientResponse = PostAnalyticsPageviewTrackpageviewClientResponses[keyof PostAnalyticsPageviewTrackpageviewClientResponses];

export type PostAnalyticsPageeventTrackpageeventData = {
    body: PageEventRequestModel;
    headers: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
        /**
         * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
         */
        'External-Visitor-Id'?: string;
        /**
         * The unique identifier of the Pageview, as retrieved via the Analytics trackpageview API.
         */
        'Pageview-Id': string;
    };
    path?: never;
    query?: never;
    url: '/umbraco/engage/api/v1/analytics/pageevent/trackpageevent';
};

export type PostAnalyticsPageeventTrackpageeventErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostAnalyticsPageeventTrackpageeventResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAnalyticsPageviewTrackpageviewServerData = {
    body: RemotePageViewServerRequestModel;
    headers?: {
        /**
         * API key specified through configuration to authorize access to the API.
         */
        'Api-Key'?: string;
        /**
         * Use this to override the default (cookie-based) visitor ID when making requests on behalf of a visitor.<br> This will impact API behaviour like querying Segmented Content, Pageview Tracking, etc.
         */
        'External-Visitor-Id'?: string;
    };
    path?: never;
    query?: never;
    url: '/umbraco/engage/api/v1/analytics/pageview/trackpageview/server';
};

export type PostAnalyticsPageviewTrackpageviewServerErrors = {
    /**
     * Payment Required
     */
    402: NotPermittedDueToLicenseResultModel;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostAnalyticsPageviewTrackpageviewServerError = PostAnalyticsPageviewTrackpageviewServerErrors[keyof PostAnalyticsPageviewTrackpageviewServerErrors];

export type PostAnalyticsPageviewTrackpageviewServerResponses = {
    /**
     * OK
     */
    200: RemotePageViewResponseModel;
};

export type PostAnalyticsPageviewTrackpageviewServerResponse = PostAnalyticsPageviewTrackpageviewServerResponses[keyof PostAnalyticsPageviewTrackpageviewServerResponses];
