//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v18.2.0+3a150af
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Generated Graphics</summary>
	[PublishedModel("generatedGraphics")]
	public partial class GeneratedGraphics : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "18.2.0+3a150af")]
		public new const string ModelTypeAlias = "generatedGraphics";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "18.2.0+3a150af")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "18.2.0+3a150af")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "18.2.0+3a150af")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<GeneratedGraphics, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public GeneratedGraphics(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Animate: Also generate a GSAP timeline. It plays once when the graphic scrolls into view, and again on hover or tap.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "18.2.0+3a150af")]
		[ImplementPropertyType("animate")]
		public virtual bool Animate => this.Value<bool>(_publishedValueFallback, "animate");

		///<summary>
		/// Animation direction: Optional. What should happen, in what order, with what feel. Left empty, the model picks the scene's natural action.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "18.2.0+3a150af")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("animationPrompt")]
		public virtual string AnimationPrompt => this.Value<string>(_publishedValueFallback, "animationPrompt");

		///<summary>
		/// Aspect ratio: e.g. 16:9 (default), 4:1, 1:1, 4:3.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "18.2.0+3a150af")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aspectRatio")]
		public virtual string AspectRatio => this.Value<string>(_publishedValueFallback, "aspectRatio");

		///<summary>
		/// Brief fingerprint: Internal: the brief the current drawing was made from.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "18.2.0+3a150af")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("generationHash")]
		public virtual string GenerationHash => this.Value<string>(_publishedValueFallback, "generationHash");

		///<summary>
		/// Status: Written by the generator on every save: model, timing, token counts, or the error.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "18.2.0+3a150af")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("generationStatus")]
		public virtual string GenerationStatus => this.Value<string>(_publishedValueFallback, "generationStatus");

		///<summary>
		/// Prompt: What to draw: subject, mood, style notes. The model draws a flat vector illustration for the dark site design.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "18.2.0+3a150af")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("prompt")]
		public virtual string Prompt => this.Value<string>(_publishedValueFallback, "prompt");

		///<summary>
		/// Reference image: Optional. A photo the model uses for subject and composition - it is sent along with the prompt.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "18.2.0+3a150af")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("referenceImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ReferenceImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "referenceImage");

		///<summary>
		/// Regenerate: Tick and save to draw again even though nothing above changed. Clears itself.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "18.2.0+3a150af")]
		[ImplementPropertyType("regenerate")]
		public virtual bool Regenerate => this.Value<bool>(_publishedValueFallback, "regenerate");

		///<summary>
		/// GSAP timeline: Body of a function (svg, gsap) returning a paused timeline. Generated when Animate is on.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "18.2.0+3a150af")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("script")]
		public virtual string Script => this.Value<string>(_publishedValueFallback, "script");

		///<summary>
		/// SVG: The drawing. Generated; hand edits survive until the brief changes or Regenerate is ticked.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "18.2.0+3a150af")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("svg")]
		public virtual string Svg => this.Value<string>(_publishedValueFallback, "svg");
	}
}
