// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 23.6.2025, 09.27.47
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["X:/kasparboelkjeldsen/kjeldsen.dev/kjeldsen.frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","X:/kasparboelkjeldsen/kjeldsen.dev/kjeldsen.frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","X:/kasparboelkjeldsen/kjeldsen.dev/kjeldsen.frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","X:/kasparboelkjeldsen/kjeldsen.dev/kjeldsen.frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","X:/kasparboelkjeldsen/kjeldsen.dev/kjeldsen.frontend/plugins/**/*.{js,ts,mjs}","X:/kasparboelkjeldsen/kjeldsen.dev/kjeldsen.frontend/composables/**/*.{js,ts,mjs}","X:/kasparboelkjeldsen/kjeldsen.dev/kjeldsen.frontend/utils/**/*.{js,ts,mjs}","X:/kasparboelkjeldsen/kjeldsen.dev/kjeldsen.frontend/pages/__blockpreview.vue","X:/kasparboelkjeldsen/kjeldsen.dev/kjeldsen.frontend/pages/__preview.vue","X:/kasparboelkjeldsen/kjeldsen.dev/kjeldsen.frontend/pages/[...slug].vue","X:/kasparboelkjeldsen/kjeldsen.dev/kjeldsen.frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","X:/kasparboelkjeldsen/kjeldsen.dev/kjeldsen.frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","X:/kasparboelkjeldsen/kjeldsen.dev/kjeldsen.frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;