// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 29.4.2025, 14.42.37
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/code/personal projects/kjeldsen.dev/kjeldsen.frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/code/personal projects/kjeldsen.dev/kjeldsen.frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/code/personal projects/kjeldsen.dev/kjeldsen.frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/code/personal projects/kjeldsen.dev/kjeldsen.frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/code/personal projects/kjeldsen.dev/kjeldsen.frontend/plugins/**/*.{js,ts,mjs}","C:/code/personal projects/kjeldsen.dev/kjeldsen.frontend/composables/**/*.{js,ts,mjs}","C:/code/personal projects/kjeldsen.dev/kjeldsen.frontend/utils/**/*.{js,ts,mjs}","C:/code/personal projects/kjeldsen.dev/kjeldsen.frontend/pages/[...slug].vue","C:/code/personal projects/kjeldsen.dev/kjeldsen.frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/code/personal projects/kjeldsen.dev/kjeldsen.frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/code/personal projects/kjeldsen.dev/kjeldsen.frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;