import json

def create_animal(name, type_, habitat, diet, lifespan, tags, primary_color, secondary_color, description):
    return {
        name: {
            "type": type_,
            "habitat": habitat,
            "diet": diet,
            "lifespan": lifespan,
            "tags": tags,
            "color-scheme": {
                "primary": primary_color,
                "secondary": secondary_color
            },
            "description100words": description
        }
    }

da_animals = [
    create_animal("alligator", "Krybdyr", "Søer, floder og sumpe", "Kødædende", "Op til 50 år", ["farlig", "stor", "vild"], "darkgreen", "brown", "Alligatorer er store krybdyr, der findes i søer, floder og sumpe. De er kødædende og kan leve op til 50 år. Alligatorer er kendt for deres stærke kæber og skarpe tænder."),
    create_animal("alpaka", "Pattedyr", "Bjerge i Sydamerika", "Planteædende", "15-20 år", ["uld", "blød", "husdyr"], "sienna", "wheat", "Alpakaen er et tæmmet kameldyr fra Sydamerika. Den er kendt for sin utroligt bløde uld."),
    create_animal("bjørn", "Pattedyr", "Skove og bjerge", "Altædende", "20-30 år", ["stærk", "pels", "vild"], "saddlebrown", "black", "Bjørne er store, kraftige pattedyr med tyk pels. De findes i mange forskellige klimaer."),
    create_animal("bæver", "Pattedyr", "Floder og søer", "Planteædende", "10-15 år", ["bygger", "vand", "tænder"], "sienna", "darkslategray", "Bævere er kendt for at bygge dæmninger og hytter af træ og mudder."),
    create_animal("chimpanse", "Pattedyr", "Regnskove", "Altædende", "40-50 år", ["klog", "social", "abe"], "black", "darksalmon", "Chimpanser er vores nærmeste nulevende slægtninge i dyreriget."),
    create_animal("cikade", "Insekt", "Træer i varme klimaer", "Plantesaft", "Få uger (efter år under jorden)", ["larmende", "vinger", "sommer"], "olivedrab", "gold", "Cikader er kendt for deres høje sang på varme sommerdage."),
    create_animal("delfin", "Pattedyr", "Have og oceaner", "Kødædende", "20-40 år", ["klog", "legende", "svømmer"], "deepskyblue", "lightgray", "Delfiner er intelligente havpattedyr, der lever i sociale grupper."),
    create_animal("dådyr", "Pattedyr", "Skove og parker", "Planteædende", "12-16 år", ["prikket", "gevir", "hurtig"], "peru", "white", "Dådyret er en mellemstor hjorteart, der er kendt for sin plettede sommerpels."),
    create_animal("elefant", "Pattedyr", "Savanner og skove", "Planteædende", "60-70 år", ["kæmpe", "snabel", "klog"], "gray", "darkgray", "Elefanter er verdens største landdyr og har en utrolig hukommelse."),
    create_animal("egern", "Pattedyr", "Skove og haver", "Planteædende", "3-7 år", ["lille", "hurtig", "hale"], "chocolate", "tan", "Egernet er en lille gnaver med en stor busket hale, der elsker nødder."),
    create_animal("flamingo", "Fugl", "Søer og laguner", "Altædende", "20-30 år", ["lyserød", "lang", "flok"], "hotpink", "pink", "Flamingoer er kendt for deres lyserøde fjerdragt og lange ben."),
    create_animal("flagermus", "Pattedyr", "Huler og skove", "Insektædende/Frugtædende", "10-30 år", ["nat", "flyvende", "radar"], "black", "dimgray", "Flagermus er de eneste pattedyr, der virkelig kan flyve."),
    create_animal("giraf", "Pattedyr", "Savanner", "Planteædende", "20-25 år", ["høj", "hals", "pletter"], "gold", "saddlebrown", "Giraffen er verdens højeste landdyr og spiser blade fra toppen af træerne."),
    create_animal("grævling", "Pattedyr", "Skove og åbne landskaber", "Altædende", "10-15 år", ["striber", "nat", "hule"], "darkslategray", "lightgray", "Grævlingen er et kraftigt bygget mårdyr med karakteristiske sorte og hvide striber i hovedet."),
    create_animal("hest", "Pattedyr", "Sletter og gårde", "Planteædende", "25-30 år", ["hurtig", "ride", "man"], "sienna", "black", "Heste har været menneskets ledsager i årtusinder til transport og arbejde."),
    create_animal("hyæne", "Pattedyr", "Savanner", "Kødædende", "12-20 år", ["latter", "jæger", "flok"], "peru", "darkkhaki", "Hyæner er dygtige jægere og ådselædere, kendt for deres 'latter'."),
    create_animal("isbjørn", "Pattedyr", "Arktis", "Kødædende", "20-25 år", ["hvid", "kulde", "stærk"], "white", "lightcyan", "Isbjørnen er verdens største landlevende rovdyr og lever på havisen."),
    create_animal("iguan", "Krybdyr", "Tropiske skove", "Planteædende", "15-20 år", ["grøn", "skæl", "kam"], "limegreen", "forestgreen", "Iguaner er store øgler, der ofte lever i træer i tropiske områder."),
    create_animal("jaguar", "Pattedyr", "Regnskove", "Kødædende", "12-15 år", ["pletter", "jæger", "kat"], "goldenrod", "black", "Jaguaren er den største kat i Amerika og en fremragende svømmer."),
    create_animal("jordegern", "Pattedyr", "Skove og huler", "Altædende", "2-3 år", ["striber", "nødder", "lille"], "saddlebrown", "wheat", "Jordegern er små gnavere med striber på ryggen, der samler forråd."),
    create_animal("kænguru", "Pattedyr", "Australiens sletter", "Planteædende", "6-20 år", ["hop", "pung", "australien"], "peru", "burlywood", "Kænguruer er pungdyr, der bevæger sig ved at hoppe på deres kraftige bagben."),
    create_animal("koala", "Pattedyr", "Eukalyptusskove", "Planteædende", "13-18 år", ["træ", "sover", "australien"], "silver", "gray", "Koalaen er et pungdyr, der lever af eukalyptusblade og sover meget."),
    create_animal("løve", "Pattedyr", "Savanner", "Kødædende", "10-14 år", ["konge", "brøl", "manke"], "gold", "darkorange", "Løven kaldes dyrenes konge og lever i flokke på den afrikanske savanne."),
    create_animal("lemur", "Pattedyr", "Madagaskar", "Altædende", "15-20 år", ["hale", "øjne", "madagaskar"], "gray", "black", "Lemurer findes kun på Madagaskar og er kendt for deres store øjne."),
    create_animal("mus", "Pattedyr", "Overalt", "Altædende", "1-2 år", ["lille", "ost", "hurtig"], "gray", "pink", "Mus er små gnavere, der findes næsten overalt i verden."),
    create_animal("muldvarp", "Pattedyr", "Under jorden", "Insektædende", "3-6 år", ["graver", "blind", "jord"], "black", "dimgray", "Muldvarpen lever det meste af sit liv under jorden, hvor den graver gange."),
    create_animal("næsehorn", "Pattedyr", "Savanner og skove", "Planteædende", "35-50 år", ["horn", "tung", "panser"], "darkgray", "gray", "Næsehorn er store, tunge dyr kendt for deres horn på snuden."),
    create_animal("narhval", "Pattedyr", "Arktiske have", "Kødædende", "30-50 år", ["horn", "hval", "vand"], "lightgray", "darkslategray", "Narhvalen er kendt som 'havets enhjørning' på grund af sin lange stødtand."),
    create_animal("odder", "Pattedyr", "Vandløb og kyster", "Kødædende", "10-15 år", ["vand", "leg", "pels"], "sienna", "saddlebrown", "Oddere er legesyge dyr, der er fremragende svømmere."),
    create_animal("okapi", "Pattedyr", "Regnskove i Congo", "Planteædende", "20-30 år", ["striber", "sjælden", "skov"], "saddlebrown", "white", "Okapien ligner en blanding af en hest og en zebra, men er i familie med giraffen."),
    create_animal("pingvin", "Fugl", "Antarktis og sydlige have", "Kødædende", "15-20 år", ["is", "svømmer", "kjole"], "black", "white", "Pingviner er fugle, der ikke kan flyve, men er mestre til at svømme."),
    create_animal("panda", "Pattedyr", "Bambusskove", "Planteædende", "20 år", ["sort-hvid", "bambus", "kina"], "white", "black", "Kæmpepandaen er kendt for sin sorte og hvide pels og sin appetit på bambus."),
    create_animal("quokka", "Pattedyr", "Øer i Australien", "Planteædende", "10 år", ["smil", "lille", "pungdyr"], "peru", "saddlebrown", "Quokkaen er kendt som verdens gladeste dyr på grund af sit smilende udtryk."),
    create_animal("quetzal", "Fugl", "Mellemamerikas skove", "Altædende", "20-25 år", ["farverig", "hale", "hellig"], "springgreen", "red", "Quetzalen er en utrolig farverig fugl med en meget lang hale."),
    create_animal("ræv", "Pattedyr", "Skove og byer", "Altædende", "2-5 år", ["snedig", "rød", "hale"], "orangered", "white", "Ræven er et klogt og tilpasningsdygtigt rovdyr med en flot rød pels."),
    create_animal("rensdyr", "Pattedyr", "Tundra og bjerge", "Planteædende", "15 år", ["gevir", "jul", "flok"], "rosybrown", "white", "Rensdyr lever i kolde nordlige egne og vandrer ofte i store flokke."),
    create_animal("slange", "Krybdyr", "Overalt undtagen polerne", "Kødædende", "10-30 år", ["lang", "gift", "kryb"], "olivedrab", "yellowgreen", "Slanger er benløse krybdyr, der findes i mange størrelser og farver."),
    create_animal("sæl", "Pattedyr", "Have og kyster", "Kødædende", "25-30 år", ["vand", "luffer", "sød"], "silver", "darkgray", "Sæler er havpattedyr, der er kluntede på land men elegante i vand."),
    create_animal("tiger", "Pattedyr", "Asiens skove", "Kødædende", "10-15 år", ["striber", "farlig", "kat"], "orange", "black", "Tigeren er verdens største kat og kendes på sine sorte striber."),
    create_animal("tukan", "Fugl", "Regnskove", "Altædende", "20 år", ["næb", "farver", "træ"], "black", "orange", "Tukanen er kendt for sit enorme og farverige næb."),
    create_animal("ugle", "Fugl", "Skove", "Kødædende", "10-20 år", ["nat", "klog", "øjne"], "saddlebrown", "tan", "Ugler er nataktive rovfugle med fantastisk syn og hørelse."),
    create_animal("ulv", "Pattedyr", "Skove og tundra", "Kødædende", "6-8 år", ["flok", "hyl", "vild"], "gray", "lightgray", "Ulven er stamfaderen til alle tamhunde og lever i tætte familiegrupper."),
    create_animal("vaskebjørn", "Pattedyr", "Skove og byer", "Altædende", "2-3 år", ["maske", "hænder", "nat"], "dimgray", "black", "Vaskebjørne er nysgerrige dyr med en sort maske og fingerfærdige poter."),
    create_animal("vildsvin", "Pattedyr", "Skove", "Altædende", "15-20 år", ["tænder", "børster", "stærk"], "saddlebrown", "black", "Vildsvinet er forfaderen til tamsvinet og har store hjørnetænder."),
    create_animal("wombat", "Pattedyr", "Australien", "Planteædende", "15 år", ["grave", "tyk", "nat"], "rosybrown", "sienna", "Wombatten er et kraftigt pungdyr, der graver store hulesystemer."),
    create_animal("wallaby", "Pattedyr", "Australien", "Planteædende", "9-15 år", ["hop", "lille", "pung"], "peru", "wheat", "En wallaby ligner en kænguru, men er typisk mindre."),
    create_animal("xenopus", "Padde", "Vand i Afrika", "Kødædende", "5-15 år", ["frø", "vand", "glat"], "olive", "darkolivegreen", "Xenopus er en slægt af frøer, der lever hele deres liv under vandet."),
    create_animal("yakokse", "Pattedyr", "Himalaya", "Planteædende", "20 år", ["bjerge", "uld", "horn"], "black", "darkslategray", "Yakoksen er tilpasset livet i de høje bjerge med sin tykke pels."),
    create_animal("zebra", "Pattedyr", "Savanner", "Planteædende", "25 år", ["striber", "sort-hvid", "hest"], "white", "black", "Zebraen er kendt for sine sorte og hvide striber, som forvirrer rovdyr.")
]

en_animals = [
    create_animal("alligator", "Reptile", "Swamps and rivers", "Carnivore", "30-50 years", ["dangerous", "teeth", "swamp"], "darkgreen", "olive", "Alligators are large reptiles native to the Americas and China."),
    create_animal("antelope", "Mammal", "Grasslands", "Herbivore", "10-25 years", ["fast", "horns", "herd"], "peru", "wheat", "Antelopes are elegant runners found mainly in Africa and Asia."),
    create_animal("bear", "Mammal", "Forests and mountains", "Omnivore", "20-30 years", ["strong", "fur", "hibernation"], "saddlebrown", "black", "Bears are large mammals found in many habitats throughout the Northern Hemisphere."),
    create_animal("beaver", "Mammal", "Rivers and ponds", "Herbivore", "10-15 years", ["dam", "teeth", "tail"], "sienna", "darkslategray", "Beavers are famous for building dams and lodges using trees and mud."),
    create_animal("cat", "Mammal", "Homes", "Carnivore", "12-18 years", ["pet", "soft", "meow"], "lightgray", "darkgray", "Cats are popular pets known for their agility and independence."),
    create_animal("camel", "Mammal", "Deserts", "Herbivore", "40-50 years", ["hump", "desert", "sand"], "tan", "burlywood", "Camels are adapted to desert life and can go for long periods without water."),
    create_animal("dolphin", "Mammal", "Oceans", "Carnivore", "20-40 years", ["smart", "playful", "swim"], "deepskyblue", "lightgray", "Dolphins are highly intelligent marine mammals known for their acrobatics."),
    create_animal("deer", "Mammal", "Forests", "Herbivore", "10-20 years", ["antlers", "gentle", "forest"], "peru", "white", "Deer are common forest animals; males often grow antlers annually."),
    create_animal("elephant", "Mammal", "Savannas and forests", "Herbivore", "60-70 years", ["huge", "trunk", "tusks"], "gray", "darkgray", "Elephants are the largest land animals and have complex social structures."),
    create_animal("eagle", "Bird", "Mountains and skies", "Carnivore", "20-30 years", ["fly", "predator", "vision"], "saddlebrown", "white", "Eagles are large birds of prey with excellent eyesight."),
    create_animal("flamingo", "Bird", "Lakes", "Omnivore", "20-30 years", ["pink", "tall", "water"], "hotpink", "pink", "Flamingos are famous for their bright pink feathers and standing on one leg."),
    create_animal("fox", "Mammal", "Forests and cities", "Omnivore", "2-5 years", ["cunning", "red", "tail"], "orangered", "white", "Foxes are small to medium-sized omnivorous mammals belonging to the dog family."),
    create_animal("giraffe", "Mammal", "Savannas", "Herbivore", "20-25 years", ["tall", "neck", "spots"], "gold", "saddlebrown", "Giraffes are the tallest mammals on Earth, browsing on high tree branches."),
    create_animal("gorilla", "Mammal", "Rainforests", "Herbivore", "35-40 years", ["strong", "ape", "forest"], "black", "dimgray", "Gorillas are the largest living primates and live in family groups."),
    create_animal("hippo", "Mammal", "Rivers", "Herbivore", "40-50 years", ["heavy", "water", "dangerous"], "gray", "lightpink", "Hippos spend most of their time in water to keep their massive bodies cool."),
    create_animal("horse", "Mammal", "Plains and farms", "Herbivore", "25-30 years", ["fast", "ride", "mane"], "sienna", "black", "Horses have been domesticated for thousands of years for transport and work."),
    create_animal("iguana", "Reptile", "Tropical forests", "Herbivore", "15-20 years", ["green", "lizard", "scales"], "limegreen", "forestgreen", "Iguanas are large lizards native to tropical areas of Central and South America."),
    create_animal("impala", "Mammal", "Savannas", "Herbivore", "12-15 years", ["jump", "fast", "antelope"], "peru", "wheat", "Impalas are medium-sized antelopes known for their incredible leaping ability."),
    create_animal("jaguar", "Mammal", "Rainforests", "Carnivore", "12-15 years", ["spots", "hunter", "cat"], "goldenrod", "black", "Jaguars are powerful big cats that are excellent swimmers and climbers."),
    create_animal("jellyfish", "Invertebrate", "Oceans", "Carnivore", "1 year", ["sting", "ocean", "transparent"], "plum", "violet", "Jellyfish are gelatinous sea creatures that drift through the ocean currents."),
    create_animal("kangaroo", "Mammal", "Australia", "Herbivore", "6-20 years", ["hop", "pouch", "australia"], "peru", "burlywood", "Kangaroos are marsupials famous for hopping on their powerful hind legs."),
    create_animal("koala", "Mammal", "Eucalyptus forests", "Herbivore", "13-18 years", ["cute", "sleepy", "tree"], "silver", "gray", "Koalas are tree-dwelling marsupials that feed almost exclusively on eucalyptus."),
    create_animal("lion", "Mammal", "Savannas", "Carnivore", "10-14 years", ["king", "roar", "mane"], "gold", "darkorange", "Lions are social big cats that live in groups called prides."),
    create_animal("lemur", "Mammal", "Madagascar", "Omnivore", "15-20 years", ["tail", "eyes", "island"], "gray", "black", "Lemurs are primates found only on the island of Madagascar."),
    create_animal("monkey", "Mammal", "Forests", "Omnivore", "10-40 years", ["climb", "tail", "smart"], "saddlebrown", "tan", "Monkeys are intelligent primates that are often arboreal and active."),
    create_animal("moose", "Mammal", "Northern forests", "Herbivore", "15-25 years", ["antlers", "huge", "forest"], "darkslategray", "black", "Moose are the largest members of the deer family, found in northern climates."),
    create_animal("narwhal", "Mammal", "Arctic Ocean", "Carnivore", "30-50 years", ["tusk", "whale", "arctic"], "lightgray", "darkslategray", "Narwhals are medium-sized whales known for the long tusk on males."),
    create_animal("newt", "Amphibian", "Ponds and streams", "Carnivore", "10-15 years", ["small", "water", "lizard-like"], "orange", "brown", "Newts are small amphibians that spend part of their lives in water."),
    create_animal("otter", "Mammal", "Waterways", "Carnivore", "10-15 years", ["swim", "playful", "fur"], "sienna", "saddlebrown", "Otters are semi-aquatic mammals known for their playful nature."),
    create_animal("owl", "Bird", "Forests", "Carnivore", "10-20 years", ["night", "wise", "fly"], "saddlebrown", "tan", "Owls are nocturnal birds of prey with silent flight and keen senses."),
    create_animal("penguin", "Bird", "Antarctica", "Carnivore", "15-20 years", ["ice", "swim", "tuxedo"], "black", "white", "Penguins are flightless birds adapted for life in the water and cold."),
    create_animal("panda", "Mammal", "Bamboo forests", "Herbivore", "20 years", ["black-white", "bamboo", "bear"], "white", "black", "Giant pandas are bears native to China that eat almost exclusively bamboo."),
    create_animal("quokka", "Mammal", "Australia", "Herbivore", "10 years", ["smile", "small", "marsupial"], "peru", "saddlebrown", "Quokkas are small marsupials known for their friendly appearance."),
    create_animal("quail", "Bird", "Fields", "Omnivore", "2-3 years", ["small", "bird", "ground"], "sienna", "wheat", "Quails are small ground-nesting birds often found in flocks."),
    create_animal("rabbit", "Mammal", "Fields and burrows", "Herbivore", "8-12 years", ["ears", "hop", "cute"], "lightgray", "white", "Rabbits are small mammals with long ears and powerful hind legs."),
    create_animal("raccoon", "Mammal", "Forests and cities", "Omnivore", "2-3 years", ["mask", "hands", "night"], "dimgray", "black", "Raccoons are adaptable mammals known for their dexterity and mask-like markings."),
    create_animal("snake", "Reptile", "Worldwide", "Carnivore", "10-30 years", ["slither", "scales", "reptile"], "olivedrab", "yellowgreen", "Snakes are elongated, legless reptiles found on every continent except Antarctica."),
    create_animal("shark", "Fish", "Oceans", "Carnivore", "20-30 years", ["teeth", "predator", "swim"], "slategray", "white", "Sharks are cartilaginous fish and apex predators of the ocean."),
    create_animal("tiger", "Mammal", "Asian forests", "Carnivore", "10-15 years", ["stripes", "big cat", "hunter"], "orange", "black", "Tigers are the largest cat species, recognizable by their dark vertical stripes."),
    create_animal("toucan", "Bird", "Rainforests", "Omnivore", "20 years", ["beak", "colorful", "bird"], "black", "orange", "Toucans are tropical birds famous for their large, colorful bills."),
    create_animal("urchin", "Invertebrate", "Oceans", "Omnivore", "30+ years", ["spiky", "round", "sea"], "purple", "black", "Sea urchins are spiny sea creatures found on ocean floors."),
    create_animal("urial", "Mammal", "Mountains", "Herbivore", "10-12 years", ["sheep", "horns", "wild"], "tan", "saddlebrown", "Urials are wild sheep found in central Asia with large curling horns."),
    create_animal("vulture", "Bird", "Open country", "Carnivore", "10-30 years", ["scavenger", "wings", "bald"], "black", "darkgray", "Vultures are scavenging birds that play a key role in cleaning up ecosystems."),
    create_animal("vole", "Mammal", "Fields", "Herbivore", "3-6 months", ["small", "mouse-like", "burrow"], "sienna", "gray", "Voles are small rodents that look similar to mice but with shorter tails."),
    create_animal("whale", "Mammal", "Oceans", "Carnivore", "40-90 years", ["huge", "ocean", "song"], "steelblue", "white", "Whales are the largest animals on Earth, roaming the world's oceans."),
    create_animal("wolf", "Mammal", "Wilderness", "Carnivore", "6-8 years", ["pack", "howl", "wild"], "gray", "lightgray", "Wolves are social predators that live and hunt in packs."),
    create_animal("xenopus", "Amphibian", "Water", "Carnivore", "5-15 years", ["frog", "water", "smooth"], "olive", "darkolivegreen", "Xenopus frogs are aquatic amphibians often used in scientific research."),
    create_animal("x-ray fish", "Fish", "Rivers", "Omnivore", "3-4 years", ["transparent", "small", "school"], "lightcyan", "silver", "X-ray fish have translucent bodies that make their backbones visible."),
    create_animal("yak", "Mammal", "Himalayas", "Herbivore", "20 years", ["furry", "mountain", "strong"], "black", "darkslategray", "Yaks are long-haired cattle adapted to living in high altitudes."),
    create_animal("zebra", "Mammal", "Savannas", "Herbivore", "25 years", ["stripes", "black-white", "herd"], "white", "black", "Zebras are African equids with distinctive black-and-white striped coats.")
]

data = {
    "da": da_animals,
    "en": en_animals
}

with open(r"x:\kasparboelkjeldsen\kjeldsen.dev\zoo\animals.json", "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
