// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44375' | (string & {});
};

export type IApiContentResponseModel = {
    contentType: null | string;
    name?: null | string;
    createDate: string;
    updateDate: string;
    route: IApiContentRouteModel;
    id: string;
    properties: null | {
        [key: string]: unknown;
    };
    cultures: null | {
        [key: string]: IApiContentRouteModel;
    };
};

export type IApiContentRouteModel = {
    path: null | string;
    queryString?: null | string;
    startItem: IApiContentStartItemModel;
};

export type IApiContentStartItemModel = {
    id: string;
    path: null | string;
};

export type IApiMediaWithCropsResponseModel = {
    path: null | string;
    createDate: string;
    updateDate: string;
    focalPoint?: ImageFocalPointModel;
    crops?: null | Array<ImageCropModel>;
    id: string;
    name: null | string;
    mediaType: null | string;
    url: null | string;
    extension?: null | string;
    width?: null | number;
    height?: null | number;
    bytes?: null | number;
    properties: null | {
        [key: string]: unknown;
    };
};

export type ImageCropCoordinatesModel = {
    x1: number;
    y1: number;
    x2: number;
    y2: number;
};

export type ImageCropModel = {
    alias: null | string;
    width: number;
    height: number;
    coordinates: ImageCropCoordinatesModel;
};

export type ImageFocalPointModel = {
    left: number;
    top: number;
};

export type PagedIApiContentResponseModel = {
    total: number;
    items: Array<IApiContentResponseModel>;
};

export type PagedIApiMediaWithCropsResponseModel = {
    total: number;
    items: Array<IApiMediaWithCropsResponseModel>;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
};

export type GetContent20Data = {
    body?: never;
    headers?: {
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Defines the segment to return. Use this when querying segment variant content items.
         */
        'Accept-Segment'?: string;
        /**
         * Whether to request draft content.
         */
        Preview?: boolean;
        /**
         * URL segment or GUID of a root content item.
         */
        'Start-Item'?: string;
    };
    path?: never;
    query?: {
        /**
         * Specifies the content items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fetch?: string;
        /**
         * Defines how to filter the fetched content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        filter?: Array<string>;
        /**
         * Defines how to sort the found content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        sort?: Array<string>;
        /**
         * Specifies the number of found content items to skip. Use this to control pagination of the response.
         */
        skip?: number;
        /**
         * Specifies the number of found content items to take. Use this to control pagination of the response.
         */
        take?: number;
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/content';
};

export type GetContent20Errors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetContent20Error = GetContent20Errors[keyof GetContent20Errors];

export type GetContent20Responses = {
    /**
     * OK
     */
    200: PagedIApiContentResponseModel;
};

export type GetContent20Response = GetContent20Responses[keyof GetContent20Responses];

export type GetContentItemById20Data = {
    body?: never;
    headers?: {
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Defines the segment to return. Use this when querying segment variant content items.
         */
        'Accept-Segment'?: string;
        /**
         * Whether to request draft content.
         */
        Preview?: boolean;
        /**
         * URL segment or GUID of a root content item.
         */
        'Start-Item'?: string;
    };
    path: {
        id: string;
    };
    query?: {
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/content/item/{id}';
};

export type GetContentItemById20Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetContentItemById20Responses = {
    /**
     * OK
     */
    200: IApiContentResponseModel;
};

export type GetContentItemById20Response = GetContentItemById20Responses[keyof GetContentItemById20Responses];

export type GetContentItemByPath20Data = {
    body?: never;
    headers?: {
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Defines the segment to return. Use this when querying segment variant content items.
         */
        'Accept-Segment'?: string;
        /**
         * Whether to request draft content.
         */
        Preview?: boolean;
        /**
         * URL segment or GUID of a root content item.
         */
        'Start-Item'?: string;
    };
    path: {
        path: string;
    };
    query?: {
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/content/item/{path}';
};

export type GetContentItemByPath20Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetContentItemByPath20Responses = {
    /**
     * OK
     */
    200: IApiContentResponseModel;
};

export type GetContentItemByPath20Response = GetContentItemByPath20Responses[keyof GetContentItemByPath20Responses];

export type GetContentItems20Data = {
    body?: never;
    headers?: {
        /**
         * Defines the language to return. Use this when querying language variant content items.
         */
        'Accept-Language'?: string;
        /**
         * Defines the segment to return. Use this when querying segment variant content items.
         */
        'Accept-Segment'?: string;
        /**
         * Whether to request draft content.
         */
        Preview?: boolean;
        /**
         * URL segment or GUID of a root content item.
         */
        'Start-Item'?: string;
    };
    path?: never;
    query?: {
        id?: Array<string>;
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/content/items';
};

export type GetContentItems20Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GetContentItems20Responses = {
    /**
     * OK
     */
    200: Array<IApiContentResponseModel>;
};

export type GetContentItems20Response = GetContentItems20Responses[keyof GetContentItems20Responses];

export type GetMedia20Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Specifies the media items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fetch?: string;
        /**
         * Defines how to filter the fetched media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        filter?: Array<string>;
        /**
         * Defines how to sort the found media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        sort?: Array<string>;
        /**
         * Specifies the number of found media items to skip. Use this to control pagination of the response.
         */
        skip?: number;
        /**
         * Specifies the number of found media items to take. Use this to control pagination of the response.
         */
        take?: number;
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/media';
};

export type GetMedia20Errors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type GetMedia20Error = GetMedia20Errors[keyof GetMedia20Errors];

export type GetMedia20Responses = {
    /**
     * OK
     */
    200: PagedIApiMediaWithCropsResponseModel;
};

export type GetMedia20Response = GetMedia20Responses[keyof GetMedia20Responses];

export type GetMediaItemById20Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/media/item/{id}';
};

export type GetMediaItemById20Errors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMediaItemById20Responses = {
    /**
     * OK
     */
    200: IApiMediaWithCropsResponseModel;
};

export type GetMediaItemById20Response = GetMediaItemById20Responses[keyof GetMediaItemById20Responses];

export type GetMediaItemByPath20Data = {
    body?: never;
    path: {
        path: string;
    };
    query?: {
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/media/item/{path}';
};

export type GetMediaItemByPath20Errors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetMediaItemByPath20Responses = {
    /**
     * OK
     */
    200: IApiMediaWithCropsResponseModel;
};

export type GetMediaItemByPath20Response = GetMediaItemByPath20Responses[keyof GetMediaItemByPath20Responses];

export type GetMediaItems20Data = {
    body?: never;
    path?: never;
    query?: {
        id?: Array<string>;
        /**
         * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        expand?: string;
        /**
         * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
         */
        fields?: string;
    };
    url: '/umbraco/delivery/api/v2/media/items';
};

export type GetMediaItems20Responses = {
    /**
     * OK
     */
    200: Array<IApiMediaWithCropsResponseModel>;
};

export type GetMediaItems20Response = GetMediaItems20Responses[keyof GetMediaItems20Responses];
