// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/content/**:slug': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[...slug]').default>>>>
    }
    '/api/content/children/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/children/[id]').default>>>>
    }
    '/api/content/navigation': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/navigation').default>>>>
    }
    '/api/github/callback': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/github/callback').default>>>>
    }
    '/api/murder/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/murder/list.get').default>>>>
    }
    '/api/murder/push': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/murder/push.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_multi_cache/purge/all': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-multi-cache/dist/runtime/server/api/purgeAll').default>>>>
    }
    '/__nuxt_multi_cache/purge/tags': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-multi-cache/dist/runtime/server/api/purgeTags').default>>>>
    }
    '/__nuxt_multi_cache/purge/:cacheName': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-multi-cache/dist/runtime/server/api/purgeItem').default>>>>
    }
    '/__nuxt_multi_cache/stats/:cacheName': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-multi-cache/dist/runtime/server/api/stats').default>>>>
    }
    '/__nuxt_multi_cache/inspect/:cacheName': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-multi-cache/dist/runtime/server/api/inspectItem').default>>>>
    }
    '/api/_mdc/highlight': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/mdc/dist/runtime/highlighter/event-handler').default>>>>
    }
  }
}
export {}